# Generated by Django 5.0.7 on 2024-11-19 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funds', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund',
            name='assigned_to',
            field=models.ForeignKey(help_text='Employee responsible for revising the Fund request.', on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='users.bankpersonnel'),
        ),
        migrations.AddField(
            model_name='fund',
            name='initiated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='users.loanprovider'),
        ),
    ]
