# Generated by Django 5.0.7 on 2024-11-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in months.'),
        ),
    ]
